Find workload based on creation time: issue #6
pensando/psm-tools pull request #37
Opened 2021-07-13 23:19 UTC by lindalwang

Requirements:
https://github.com/pensando/psm-tools/issues/6

2021-07-14 00:55 UTC, jainvipin requested changes
@lindalwang - thanks for your contribution! A few comments on this PR; pls address these.
I alos think we may need to expand the function of this app to do more; I will provide more comments after these comments are addressed.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +
pls include `│#!/usr/bin/python3` in the beginning of the file so there is no confusion on which binary should be used to run this binary.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +
also `chmod +x find_workload.py` when you check in so perms have the execute permissions

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +from tzlocal import get_localzone
does this package need to be pyinstalled into the repo? I am getting error trying to run this
```# ./find_workload.py 
Traceback (most recent call last):
  File "./find_workload.py", line 9, in <module>
    from tzlocal import get_localzone
ModuleNotFoundError: No module named 'tzlocal'```

If it is not used, pls remove this.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +PST = pytz.timezone('US/Pacific')
why PST? User may not be in PST; can we pick this up from the current timezone on the machine this program is being executed?

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +PST = pytz.timezone('US/Pacific')
this may be a good candidate for making a common utility function to fix this

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +parser.add_argument("-a", "--age", dest="age", help="creation date: <number>d|w|m")
can we have --help to also display some examples too for user to get some quick commands right away?

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +parser.add_argument("--dsc", dest="dsc", help = "MAC address of DSC" )
why only `--age` has abbreviated option `-a` but the others don't? can we we be consistent?

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +workload = api_instance.list_workload(o_tenant = 'default')
can you use the default tenant from a constant/var defined up at the top, allow user to specify the tenant that overrides this value.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +parser.add_argument("--dsc", dest="dsc", help = "MAC address of DSC" )
help says 'MAC address of DSC' is it the MAC of DSC or the name of DSC that looks like a MAC address? It is visually not differ, but still relevant.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    key = args.label.split(":")[0]
if the label isn't formatted as `key:value` then this gives a backtrace; can we suggest user what input to provide?
```# ./find_workload.py --label foo
Traceback (most recent call last):
  File "./find_workload.py", line 86, in <module>
    value = args.label.split(":")[1]
IndexError: list index out of range```

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    value = args.label.split(":")[1]
same problem with other parameter validation; let's add validation for all parameters
```
# ./find_workload.py --label foo:-1
Traceback (most recent call last):
  File "./find_workload.py", line 91, in <module>
    if value in item.get('meta').get('labels').get(key):
TypeError: argument of type 'NoneType' is not iterable
```

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    desired_time = current_time - datetime.timedelta(weeks = int(8))
can we make `int(8)` a variable/constant, which seems to be used as a default; also provide a comment describing its purpose.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +if not args.age:
can we put `if not args.age` as `else` to the previous `if`

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    date_number = int(args.age[0:-1])
need validation

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    if date_type == "m":
can use specify 
```
./find_workload.py --age blah    
Traceback (most recent call last):
  File "./find_workload.py", line 48, in <module>
    date_number = int(args.age[0:-1])
ValueError: invalid literal for int() with base 10: 'bla
'```

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    elif date_type == "w":
`m` can be `months`
`w` can be `weeks`
`d` can be `days`
allow user to be inclusive on input values; also the value must be 3m, 4w, etc. add validation for that as per above, ti should have numbers followed by qualification.

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +        desired_time = current_time - datetime.timedelta(days = int(date_number))
if user doesn't specify anything do you want to take it in `weeks` and print to the user something like
```
$./find_workload.py --age 5
finding the workloads created in last 5 weeks
<actual output follows that here>
```

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    print(workload_list)
This print must be tabular print unless user specifies `--json` flag i.e. something that is easy to consume
```
workload-name           labels           creation-time         
----------------        -------          --------------
workload1               foo              <time>
workload2               bar              <time>
```

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +        if args.dsc in item.get('spec').get('interfaces')[0].get('mac_address'):
can this statement result into an error of #interfaces are zero and you are indexing into the value?

2021-07-14 00:55 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    key = args.label.split(":")[0]
why is it giving me an error even when I specify the label properly?
```
./find_workload.py --label foo:bar
Traceback (most recent call last):
  File "./find_workload.py", line 91, in <module>
    if value in item.get('meta').get('labels').get(key):
TypeError: argument of type 'NoneType' is not iterable
```

2021-07-16 00:23 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +PST = pytz.timezone('US/Pacific')
The PSM is now in UTC time. Should I just delete this line and leave it as it is? Or should I change it to a user input parameter?

2021-07-16 23:35 UTC, RishabhPatil requested changes

2021-07-16 23:35 UTC, RishabhPatil commented on pyclient/apps/find_workload.py
> +if args.label:
If user enters an invalid argument for "label" this would throw an error. You may want to raise a custom exception.

2021-07-16 23:38 UTC, RishabhPatil commented on pyclient/apps/find_workload.py
> +            if value in item.get('meta').get('labels').get(key):
Any reason why you use .get and [index] interchangeably?
Usually you should use .get when you expect a NoneType and would like to set a default value

2021-07-16 23:48 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +PST = pytz.timezone('US/Pacific')
what I am suggesting is that you find out the local time of the user in the current machine and use that

2021-07-16 23:50 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    print(workload_list)
nope, most of the fields... I didn't type it up fully; but name/labels/tenant(if not default)/other relevant spec/status fields

2021-07-19 08:17 UTC, jainvipin requested changes
@lindalwang - pls submit a PR with the changes. While most of the resolved comments are really no resolved if the corresponding changes are not done.

2021-07-19 08:17 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +    date_number = int(args.age[0:-1])
I am not sure why this comment was resolved, but without actually trying to split the args.arge, and validating the value of date_number this comment can be resolved

2021-07-19 08:17 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +
can you please make the above change and submit the PR before resolving the comments?

2021-07-19 08:17 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +from tzlocal import get_localzone
comment  resolved but the code still contains this code that doesn't compile.

2021-07-19 19:48 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +            if value in item.get('meta').get('labels').get(key):
ok, I changed the format to [index]

2021-07-19 20:12 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +if args.label:
Thanks for the reminder, Vipin also noted this in the previous comment. I've made the change.

2021-07-19 21:56 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +    print(workload_list)
ok thanks. I added more fields

2021-07-19 21:57 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +PST = pytz.timezone('US/Pacific')
ok, I added the local timezone

2021-07-22 18:48 UTC, jainvipin requested changes
@lindalwang - thanks for the PR! pls find some comments in here.

2021-07-22 18:48 UTC, jainvipin commented on pyclient/requirements.txt
> +tabulate==0.8.9
wasn't there a separate PR for that; it is usually not a good idea to mix unrelated things in one PR

2021-07-22 18:48 UTC, jainvipin commented on pyclient/apps/find_workload.py
> +        print(tabulate(final_dict, headers=["workload_name", "creation_time", "labels", "tenant", "host_name", "mac_address", "ip_address", "external_vlan", "network"]))
remove "external_vlan" from this list; it will keep the output manageable
also ideally if you can be smart about not displaying "tenant" if all belong to default tenant that'd keep the outupt succinct.

2021-07-22 19:21 UTC, lindalwang commented on pyclient/requirements.txt
> +tabulate==0.8.9
Yes, sorry I accidentally added it. I will delete this file for this PR.

2021-07-22 19:21 UTC, lindalwang commented on pyclient/apps/find_workload.py
> +        print(tabulate(final_dict, headers=["workload_name", "creation_time", "labels", "tenant", "host_name", "mac_address", "ip_address", "external_vlan", "network"]))
Ok I will fix that.

2021-07-27 14:59 UTC, jainvipin commented
@lindalwang - can you please fix the following errors:
1. when label is specified I get the following

2021-08-03 00:06 UTC, jainvipin approved these changes
LGTM!

2021-08-03 00:06 UTC, RishabhPatil approved these changes
LGTM!

2021-08-03 00:06 UTC, merged