Issue #20
pensando/psm-tools pull request #38
Opened 2021-07-15 21:40 UTC by vihaanko

Code for poke a hole into a firewall

2021-07-17 00:01 UTC, jainvipin reviewed
@vihaanko - thanks for the contribution!
Please find some comments inline... I will check if the error conditions on rule matching are correct.

2021-07-17 00:01 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +    print("Rule forced. New policy created!")
minor: `New policy with specified rule created`

2021-07-17 00:29 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    print("Rule forced. New policy created!")
Fixed

2021-07-17 00:29 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    # print(p)
Fixed

2021-07-17 00:30 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +                      from_ip_addresses = [args.frm],
When reading the input as "from", the compiler recognizes it as the keyword from, so I used "frm" as an alternative. Let me know what you think.

2021-07-17 00:36 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +            print("Cannot connect, please check your connection.")
Fixed

2021-07-17 00:38 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +           print("Policy doesn't exist. Please choose the policy out of the following or do -f to create a new policy:")
Fixed

2021-07-17 00:39 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +               print(realPolicy.meta.name)
No, I don't have a loop for debugging. What should the debug loop be doing? Should it tell the user the http response?

2021-07-18 00:18 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +               print(realPolicy.meta.name)
Just to clarify, it isn't a debug statement, it is meant to list all the policies which exist to the user if the user gives a non existing policy name.

2021-07-18 02:01 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +inputPort = SecurityProtoPort(ports = args.port, protocol = "tcp")
Fixed

2021-07-18 02:18 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +                      from_ip_addresses = [args.frm],
Nevermind, I figured it out and fixed it.

2021-07-18 03:07 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +rule = SecuritySGRule(action = 'permit',
Fixed, user can also specify reject as an action.

2021-07-19 08:11 UTC, jainvipin requested changes
@vihaanko - a few more comments! thanks for incorporating remaining comments.

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +           print("Policy doesn't exist. Please choose the policy out of the following or do -f to create a new policy:")
I had actually meant to change hte error message to
```print("Policy doens't exist. Use force option i.e. `-f` to create one if desired```

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +               print(realPolicy.meta.name)
ah, got it; however isn't it a good idea to suggest that the list is a hint to specify the possible policy names or something like 
```Couldn't find the policy, use `-f` to create a new policy, or use from the following existing policies```
then display all the names?

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +            print("Cannot connect, please check your connection.")
I meant if you can change the error message to enlist all errors that could result into 409 error code? Will it not happen if the PSM IP is old, or if PSM is down?

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +rule = SecuritySGRule(action = 'permit',
I meant if you can ask optionally ask user for the option to create a deny rule, by specifying `--action` argument like `--port` and other arguments

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +    print("Hole Poked! New rule is first rule in policy.")
replace the message with "Successfully added the specified rule at the top of the specified policy"

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +    print("Rule forced. New policy created!")
Replace with "Creating policy <policuname>"

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +        print("Rule doesn't exist double check your inputs!")
specify the rule info in the message `rule <blah> doesn't exist`
remove "double check your inputs part of the error message"

2021-07-19 08:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--patch', default=False, action="store_true")
replace `patch` with `update` in the code and error messages.

2021-07-19 17:05 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +               print(realPolicy.meta.name)
Yup, that's what I am doing.

2021-07-19 17:26 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    print("Hole Poked! New rule is first rule in policy.")
Fixed

2021-07-19 17:27 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    print("Rule forced. New policy created!")
Fixed

2021-07-19 17:40 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +        print("Rule doesn't exist double check your inputs!")
Fixed

2021-07-19 17:47 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--patch', default=False, action="store_true")
Should I change the entire command's purpose or just the name. If it is just the name, then the user may get confused because the code for patch specifically deletes the rule. If it's the entire command, then should I have sub commands like "add, delete, modify" like Issue #13.

2021-07-22 18:42 UTC, jainvipin requested changes
@vihaanko - pls find some comments inline here...

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--patch', default=False, action="store_true")
just change the name; to be inline with CRUD (Create, read, updated, delete) convention

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +    print("Cannot put port number for icmp protocol")
do you want to return here instead of going further executing this binary...
this comment is applicable for the entire program

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +        print("Your protocol must be tcp, udp, or icmp")
minor: remove "your" from the message

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +                print("Couldn't find the policy, use `-f` to create a new policy, or use from the following existing policies:")
it is bit fancy, but "or use from following existing policies:" only makes sense if there are any policies returned by the comment below. Can we be smart about this comment and show it only if we sees something in the list?

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
please change `frm` to `from` here and in rest of the code.

2021-07-22 18:42 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +        api_instance.update_network_security_policy("default", args.name, policy)
can you use "default" from a variable, so we can replace it with the value if use wants to pass the value later you don't have to change this at multiple places.

2021-07-22 19:10 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
from is a keyword so I am referring to it as frm but the user can still pass input as --from.

2021-07-22 19:26 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +        print("Your protocol must be tcp, udp, or icmp")
Fixed

2021-07-22 20:56 UTC, RishabhPatil requested changes

2021-07-22 20:56 UTC, RishabhPatil commented on pyclient/apps/rule_poke.py
> +#Seperate protocol from port number
Looks like this is a common block of code which will be used quite often, can you put it in a function and move to utils

2021-07-22 20:56 UTC, RishabhPatil commented on pyclient/apps/rule_poke.py
> +    def addRule(r, p):
Can you separate your main logic and these helper functions.
It'll make your code much easier to read.

2021-07-22 20:56 UTC, RishabhPatil commented on pyclient/apps/rule_poke.py
> +            raise Exception
Try leaving a hint/message as to why this error occured.

2021-07-22 20:56 UTC, RishabhPatil commented on pyclient/apps/rule_poke.py
> +parser = argparse.ArgumentParser()
Just like the other PR, please add some help text

2021-07-22 20:56 UTC, RishabhPatil commented on pyclient/apps/rule_poke.py
> +string = "tcp/80"
Do you need this string variable?

2021-07-26 23:10 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
ok then we can make it `from-ip` in the user input.

2021-07-26 23:11 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +string = "tcp/80"
I think string variable is better be ause you can parse it to various other forms as well tomorrow e.g. if user mistypes this to `tCP/80` we can be a bit more accommodating there.

2021-08-03 18:51 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    print("Cannot put port number for icmp protocol")
Fixed

2021-08-03 18:52 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
Fixed

2021-08-03 18:58 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +                print("Couldn't find the policy, use `-f` to create a new policy, or use from the following existing policies:")
Fixed

2021-08-03 18:59 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +        api_instance.update_network_security_policy("default", args.name, policy)
Fixed

2021-08-03 20:02 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +#Seperate protocol from port number
Fixed

2021-08-03 20:04 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +    def addRule(r, p):
Fixed

2021-08-03 20:05 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +            raise Exception
Fixed

2021-08-03 20:06 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser = argparse.ArgumentParser()
So a command which displays possible actions and commands?

2021-08-04 22:56 UTC, jainvipin requested changes
@vihaanko - some comments inline...

2021-08-04 22:56 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--name', type=str, required=True)
need to add help strings for these options, e.g. `--name` is very generic this is really a policy name

2021-08-04 22:56 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
can we remove `--frm` altogether? I mean why is `--from` not sufficient?

2021-08-04 22:56 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +                print("Couldn't find the policy, use `-f` to create a new policy, or use from the following existing policies:")
can you pls change `-f` to `--force` because that's the option you are using in the args.

2021-08-04 22:56 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +# Creates the first rule in an empty policy(empty policy can happen when someone forces a hole and then patches the hole after)
is it worth adding a rule that already exist? e.g. if I do following back to back 10 times
```
./apps/rule_poke.py --action permit --frm 6.6.6.6 --to 7.7.7.7 --port tcp/454 --name test6
```
then it will add 10 rules the redundant rule is really something not useful so if a rule exist it would be good if we can say that the rule exists instead of adding another rule at the top

2021-08-04 22:56 UTC, jainvipin commented on pyclient/apps/rule_poke.py
> +# Deletes the given rule from the given policy. This is useful for when the user wants to patch a hole.
if I delete a rule that doesn't exist, I get the following backtrace, can we add something user meaningful instead?
```
# ./apps/rule_poke.py --action permit --frm 6.6.6.6 --to 7.7.7.7 --port tcp/454 --name test6 --patch
Unable to patch, given inputs are wrong. Check your rule and your policy.
Rule {'action': 'permit',
 'from_ip_addresses': ['6.6.6.6'],
 'proto_ports': [{'ports': '454', 'protocol': 'tcp'}],
 'to_ip_addresses': ['7.7.7.7']} doesn't exist
```

2021-08-09 17:33 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--name', type=str, required=True)
Fixed

2021-08-09 18:31 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +# Creates the first rule in an empty policy(empty policy can happen when someone forces a hole and then patches the hole after)
Fixed

2021-08-09 18:32 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +# Deletes the given rule from the given policy. This is useful for when the user wants to patch a hole.
Fixed

2021-08-10 02:40 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--patch', default=False, action="store_true")
But that command is to only delete a rule. Not add or update one.

2021-08-10 18:02 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +parser.add_argument('--frm', '--from', type=str, required=True)
Fixed

2021-08-10 18:03 UTC, vihaanko commented on pyclient/apps/rule_poke.py
> +                print("Couldn't find the policy, use `-f` to create a new policy, or use from the following existing policies:")
Fixed

2021-08-12 01:08 UTC, RishabhPatil reviewed
LGTM!

2021-08-12 01:09 UTC, RishabhPatil approved these changes

2021-08-12 01:09 UTC, merged