created the new API that will get the dsc from a specific workload
pensando/psm-tools pull request #39
Opened 2021-07-16 19:04 UTC by kiwb

This API is written to ease the process of finding a dsc from a specific workload. It is in the utils folder and can be imported easily.

2021-07-19 07:50 UTC, jainvipin requested changes
@kiwb - some comments...

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +        client = api_client.ApiClient(config)
if we take client just as an argument to the __init__ this means this utility can be only used when the caller has initialized the client and passes it as an arg. This will remove the need for accessing HOME/environment, psm_config_path, etc.

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +class getDscFromWorkload():
create a class for what should be a function is too granular; if you want to make a class called workload and having a function within the class to get DSC from workload could be a function; on the same note, I'd suggest changing the file name to workload.py (as this file could hold all workload utils).

Pls change the filename; I'd also remove the class for now just create a global utils like `def getDscFromWorkload(client, workload, type=0)`. If it is a class then it must include more utility functions in the future and we don't want to lock ourselves in with some name that doesn't withstand the test of time.

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +                This value is set to 0 by default
can you avoid this argument all together i.e. take workload name as a string, and try to interpret this as an IP address, if not search it as a name. i.e. if you see `a.b.c.d` kind of notation (not exact, but numbers an dots in between) then try to interpret as an IP otherwise use it as workload name

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +        if (type == 0):
change this logic based on identification of the input parameter. Also put validation if the workload specified is an IP address, then it must adhere to the workload IP format. Not sure if user will ever specify the UUID, so assume that workload IP or name is used, not uuid.
The workload IP is part of workload status field (if present), there is a possibility that workload IP is not present in which case you can report that workload was not found if IP was specified.

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +            raise ValueError("Workload not found or type is invalid.")
A few points:
1. if you don't specify type this error message should change to workload not found;
2. error message must be precise i.e. if it is workload that couldn't be found, or if the type is invalid; can't leave user to guess and figure it out.
3. A function should never raise an exception, what if caller has some elegant way to handle it; instead return error

2021-07-19 07:50 UTC, jainvipin commented on pyclient/utils/get_dsc_from_workload.py
> +        These series of statements finds the dsc's id based on the interface mac address. The return will be null if the dsc id cannot be found
this comment is for which part of the code?

2021-07-22 18:33 UTC, jainvipin requested changes
@kiwb - a few comments here.
Can you also pls rename the file to be workload_utils.py
We also need test cases for workload_utils_test.py to exercise your API with various possible arguments.

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +    if len(a) != 4:
Even if you find a few `.` it may be a mistyped IP e.g. `10.11.2` instead of `10.1.1.2` - the way to confirm is if there are numbers in the split strings then it is an IP otherwise not.
Also for IPv6 the format is a bit different uses colon, so you might want to write a separate routine which takes and IP and confirms if the string is an IPv4 or IPv6 address. Make that utility outside workload_tools.py but net_utils.py;
Also rename workload_tools.py to workload_utils.py

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +                isIP = False
It is best to write test cases for the utilities i.e. write workload_utils_test.py that calls your API with various combinations.

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +    This section checks if the name is a valid IP address, else it treats the workload param as a name. If forceName is set to true, then it will treat it a name, not an IP
IS this comment misplaced?

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +        interfaceFound = False
Do we need this variable? can we find this out from endpoint_list - if is empty then we didn't find it otherwise we did. This comment is applicable throughout this program.

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +    workload_response = workload_instance.list_workload("default", _check_return_type=False)
can you use the default tenant from a variable so if tomorrow we want to pass tenant as an arg then we don't need to change this at multiple places.

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +            return "Workload IP not found"
So is the return value a string or a list of strings (DSC names), in case of error we return a string otherwise a list? This may be confusing to the caller, why nto return two args, (error, []string) so if there is no errror DSC list is looking good.

2021-07-22 18:33 UTC, jainvipin commented on pyclient/utils/workload_tools.py
> +    These series of statements finds the dsc's id based on the endpoints. The return will be null if the dsc id cannot be found
minor: "put the comments before the code, if someone has read the code then comment is not of much value; this is the convention developers use, put a comment above the code.
Also avoid using "These series of statements" in comments

2021-07-22 21:25 UTC, RishabhPatil requested changes

2021-07-22 21:25 UTC, RishabhPatil commented on pyclient/utils/workload_tools.py
> +            return "Workload IP not found"
You can use logging.error to raise exceptions along with an error message

2021-07-22 21:25 UTC, RishabhPatil commented on pyclient/utils/workload_tools.py
> +    workload_response = workload_instance.list_workload("default", _check_return_type=False)
Any reason why you set `_check_return_type = false`?

2021-07-22 21:25 UTC, RishabhPatil commented on pyclient/utils/workload_tools.py
> +        for work in workload_response._data_store["items"]:
Please used the member variables directly instead of using _data_store.


I just tried out your code, I seem to be able to access workload_response.items

2021-07-22 21:25 UTC, RishabhPatil commented on pyclient/utils/workload_tools.py
> +                dsc_id_list.extend(endpoint["spec"]["node-uuid-list"])
I think it should be "node_uuid_list"

2021-07-23 17:16 UTC, kiwb commented on pyclient/utils/workload_tools.py
> +    workload_response = workload_instance.list_workload("default", _check_return_type=False)
I set check_return_type to false becasue then its easier to go through the response of the API call

2021-07-23 17:18 UTC, kiwb commented on pyclient/utils/workload_tools.py
> +                dsc_id_list.extend(endpoint["spec"]["node-uuid-list"])
i checked the json output in postman, it uses hyphens for this one

2021-07-23 17:26 UTC, kiwb commented on pyclient/utils/workload_tools.py
> +            return "Workload IP not found"
if i were to return two args (error, []string), should i return an empty error string when there is no error and an empty list of strings if there is an error?

2021-07-27 18:37 UTC, jainvipin requested changes
@kiwb - some comments inline.
Btw, net_utils_test.py is missing i.e. test cases for the utils code.

2021-07-27 18:37 UTC, jainvipin commented on pyclient/utils/workload_utils_test.py
> +print(getDscFromWorkload(client, "default" , "workload-host-2-w7"))
you should get all workloads and then query the one that exist. This test is bound to fail if executed on another system.

2021-07-27 18:37 UTC, jainvipin commented on pyclient/utils/workload_utils_test.py
> +print(getDscFromWorkload(client, "default" , "invalid-workload-name"))
same here, what if someone created a workload name `invalid-workload-name`?

2021-07-27 18:37 UTC, jainvipin commented on pyclient/utils/workload_utils.py
> +        if (len(endpoint_list) == 0):
minor: this logic seems to repeat `if len(endpoint_list) == 0`, would it be better if you put something like this after your else statement
```
if (len(endpoint_list) == 0):
    return "workload not found", []
```
I understand error message is not precise here but you can compensate that by printing the owrkload in error message

2021-07-27 20:09 UTC, RishabhPatil requested changes

2021-07-27 20:09 UTC, RishabhPatil commented on pyclient/utils/workload_utils.py
> +    endpoint_response = workload_instance.list_endpoint(tenant, _check_return_type=False)
Can you remove `_check_return_type=False`, it is important to run type checks on all the objects.

I just tried running your test locally, the only change you need to make after this is `endpoint["spec"]["node-uuid-list"]` to `endpoint["spec"]["node_uuid_list"]` or `endpoint.spec.node_uuid_list`

2021-08-12 00:53 UTC, RishabhPatil approved these changes
LGTM!

2021-08-12 00:53 UTC, jainvipin approved these changes
LGTM!

2021-08-12 00:54 UTC, merged