Issue #13
pensando/psm-tools pull request #44
Opened 2021-07-21 22:31 UTC by vihaanko

Checkout the code. Let me know if I should add more features.

2021-07-22 19:31 UTC, jainvipin requested changes
@vihaanko - my comments inline...

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +parser.add_argument('--command', choices=['add', 'delete', 'modify'], type=str, required=True)
let's avoid command itself as an command option i.e have add/delete/update be the commands and not options so the output could look like
```
rule.py add <policy-name> --ip <ip-address> . . .
rule.py update <policy-name> --ip <ip-address> . . . 
```

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +parser.add_argument('--nAction', type=str, required=False)
`nAction`, `nIP`, `nPort` is too cryptic; can we change this to `new-ip`, "new-port", and "new-action" instead and move them into newIp, newPort and newAction variables in the args?

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +if (args.command == "modify"):
let's use `updated` to be consistent across various other commands i.e. patch vs modify vs. udpate

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +def portValid(protocol, portNumber):
this logic seems common between this code and rule_poke.py. Can we do the port validation outside in utils/rule_utils.py instead of this file? I mean others can benefit from this logic as well

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        for i in c.split():
do we specify the split field like `/`

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        return("Rule doesn't exist. Double check your inputs!")
replace the error with "Unable to delete a rule: rule not found"

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        api_instance.update_network_security_policy("default", name, policy)
use default from a variable in case this all is needed to be done for a specified tenant.

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +def handleErrorResponse(response):
it would make sense to make this a common utility routine instead keeping this here. A routine that returns string for the error string for http return codes.

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +    (nProtocolValid, error) = portValid(nProtocol, nPortNumber)
suggest combining portRead() and portValid() into one external util function used by others

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        sys.exit("No changes made because no new values specified...")
replace with "require new values of [ip, action, port] for modify operations"

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        sys.exit("nAction, nIp, and nPort are only valid for the modify command")
suggest "new values of [ip, port, action] are not required when adding a rule"

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +(protocolValid, error) = portValid(protocol, portNumber)
can you do this portRead() and portValid() once for both create and update? before you do the update/create operation as part of the parameter validation?

2021-07-22 19:31 UTC, jainvipin commented on pyclient/apps/rule.py
> +        policy = SecurityNetworkSecurityPolicy(meta=ApiObjectMeta(name=name),
for adding a rule, if a rule already exist, do you really replace the rule or add one more similar rule on top of it?
Ideally add/update are same except update need to bail out if rule doesnt' exist and add warns/rule-out if a rule exist

2021-07-22 20:48 UTC, RishabhPatil requested changes

2021-07-22 20:48 UTC, RishabhPatil commented on pyclient/apps/rule.py
> +    if (protocol != "tcp" and protocol != "udp" and protocol != "icmp"):
In case you didnt know you can use `protocol not in ['tcp', 'udp', 'icmp']` instead of multiple `and`s

2021-07-22 20:48 UTC, RishabhPatil commented on pyclient/apps/rule.py
> +# Command line processing
Can you put this block of code under `if __name__ == '__main__':`

2021-07-22 20:48 UTC, RishabhPatil commented on pyclient/apps/rule.py
> +# Command line processing
Also, please add some help text along with each argument

`parser.add_argument('--src-ip', type=str, help='Source IP address for the rule')`

2021-07-22 20:48 UTC, RishabhPatil commented on pyclient/apps/rule.py
> +rule = SecuritySGRule(action=args.action,
You are creating a rule from one IP to the same IP. Are you sure this is the expected behaviour?

2021-07-22 20:48 UTC, RishabhPatil commented on pyclient/apps/rule.py
> +def handleErrorResponse(response):
Also, please use logging.error to raise exceptions.
You can also use response.raise_for_status() instead of checking each error code and returning an error.
https://docs.python-requests.org/en/master/api/#requests.Response.raise_for_status

2021-07-26 18:57 UTC, vihaanko commented on pyclient/apps/rule.py
> +if (args.command == "modify"):
modify is one of the three commands given in the prompt. Add, Delete, and Modify a rule. That condition is checking whether or not the command is modify, in which case, more inputs need to be provided by the user.

2021-07-26 18:58 UTC, vihaanko commented on pyclient/apps/rule.py
> +        return("Rule doesn't exist. Double check your inputs!")
Fixed

2021-07-26 18:59 UTC, vihaanko commented on pyclient/apps/rule.py
> +rule = SecuritySGRule(action=args.action,
In the prompt the user is only providing one IP address. Is there a different way of creating a rule with only one IP address?

2021-07-27 18:22 UTC, vihaanko commented on pyclient/apps/rule.py
> +        for i in c.split():
Yes. But even if the user doesn't put a slash, it can still read the protocol and port number.

2021-07-27 18:25 UTC, vihaanko commented on pyclient/apps/rule.py
> +        sys.exit("No changes made because no new values specified...")
Before this line of code, any new values which aren't specified for the modify command, are set to the old values. This way, the user only has to specify what he wants to change. This line of code is fixing the condition of the user not specifying any new values.

2021-07-27 18:25 UTC, vihaanko commented on pyclient/apps/rule.py
> +        sys.exit("nAction, nIp, and nPort are only valid for the modify command")
Fixed

2021-07-27 18:37 UTC, vihaanko commented on pyclient/apps/rule.py
> +        policy = SecurityNetworkSecurityPolicy(meta=ApiObjectMeta(name=name),
Update isn't updating the policy by adding a new rule. Update is for replacing an old rule with a new rule. I just changed my code to say "Rule already exists" if the user is trying to add an existing rule.

2021-07-27 18:39 UTC, vihaanko commented on pyclient/apps/rule.py
> +        api_instance.update_network_security_policy("default", name, policy)
Fixed

2021-07-28 04:17 UTC, vihaanko commented on pyclient/apps/rule.py
> +def portValid(protocol, portNumber):
Fixed

2021-07-28 04:17 UTC, vihaanko commented on pyclient/apps/rule.py
> +def portValid(protocol, portNumber):
Fixed

2021-08-03 21:40 UTC, vihaanko commented on pyclient/apps/rule.py
> +    (nProtocolValid, error) = portValid(nProtocol, nPortNumber)
Fixed

2021-08-04 19:22 UTC, vihaanko commented on pyclient/apps/rule.py
> +    if (protocol != "tcp" and protocol != "udp" and protocol != "icmp"):
Fixed

2021-08-04 19:24 UTC, vihaanko commented on pyclient/apps/rule.py
> +# Command line processing
Which block of code? The response handling or param processing?

2021-08-04 19:33 UTC, vihaanko commented on pyclient/apps/rule.py
> +# Command line processing
Fixed the help text. Please clarify first comment.

2021-08-04 19:34 UTC, vihaanko commented on pyclient/apps/rule.py
> +(protocolValid, error) = portValid(protocol, portNumber)
Fixed

2021-08-04 19:40 UTC, vihaanko commented on pyclient/apps/rule.py
> +parser.add_argument('--command', choices=['add', 'delete', 'modify'], type=str, required=True)
Fixed

2021-08-04 22:11 UTC, jainvipin requested changes
@vihaanko - some comments inline...

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +        print("Policy doesn't exist. Please choose the policy out of the following or use -f to create one if desired:")
it doesn't looke like `-f` option is allowed in this so perhaps you shouldn't suggest this; may be this is a copy/paste error.
If you want to allow this, then you can keep this comment and make `--force` or `-f` (ideally both one abbreviated version, one not) as a way to create a new policy

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +parser.add_argument('--name', type=str, required=True, help = 'Name of policy to preform commmand on')
accidentally I specified the name twice and it probably took the later one; is this expected?
```
 ./apps/rule.py --add --name foo --ip 6.6.6.6 --port tcp/2020 --action permit --name test6
Rule appended to policy!
```

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +        return("Rule doesn't exist. Double check your inputs!")
can you pls replace this error message with above suggestion instead of what exists here

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +parser.add_argument('--ip', type=str, required=True, help = 'Ip address for rule')
there should be two parameters `--src_ip` and `--dest_ip` and same for `new_src_ip` and `new_dest_ip` today the rule is created with same src and dest

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +        api_instance.update_network_security_policy("default", name, policy)
can you pls fix this? use `default` from a define up at the top so later if tenant comes from an arg we can use the updated value of that variable?

2021-08-04 22:11 UTC, jainvipin commented on pyclient/apps/rule.py
> +        return("Rule deleted!")
If I have a policy with two rules matching the same parameters, it only deletes one of them, can we delete both rules?

2021-08-09 19:28 UTC, vihaanko commented on pyclient/apps/rule.py
> +        print("Policy doesn't exist. Please choose the policy out of the following or use -f to create one if desired:")
Fixed

2021-08-09 20:29 UTC, vihaanko commented on pyclient/apps/rule.py
> +parser.add_argument('--add', default=False, action="store_true")
Not sure how do this. In a another program I only had one command option, so I was able to take it in a positional argument. But for this program I have three optional arguments.

2021-08-09 20:55 UTC, vihaanko commented on pyclient/apps/rule.py
> +parser.add_argument('--name', type=str, required=True, help = 'Name of policy to preform commmand on')
Is there a way to check wether or not a argument was specified twice?

2021-08-09 21:42 UTC, vihaanko commented on pyclient/apps/rule.py
> +parser.add_argument('--ip', type=str, required=True, help = 'Ip address for rule')
Fixed

2021-08-09 22:10 UTC, vihaanko commented on pyclient/apps/rule.py
> +        return("Rule deleted!")
Fixed

2021-08-10 22:13 UTC, vihaanko commented on pyclient/apps/rule.py
> +parser.add_argument('--add', default=False, action="store_true")
Fixed

2021-08-12 00:05 UTC, RishabhPatil approved these changes
LGTM!

2021-08-12 00:06 UTC, jainvipin approved these changes

2021-08-12 00:06 UTC, merged