Find policies/rules which apply to a certain workload
pensando/psm-tools pull request #48
Opened 2021-07-29 18:17 UTC by vihaanko

Take a look at my code for Issue #12. I am yet to do the range check for the IP. So just take a look at what I have so far.

2021-08-13 00:02 UTC, jainvipin requested changes
@vihaanko - pls address some comments; thanks for the PR !!

2021-08-13 00:02 UTC, jainvipin commented on pyclient/apps/find_rule.py
> +                    print(rule)
seems like a debug print that sneaked in the output; either remove or put it under `--debug`

2021-08-14 20:43 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +import os
Fixed

2021-08-14 20:44 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +parser.add_argument('--name', type=str, required=True)
Fixed

2021-08-14 20:44 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +# print(workload)
Fixed

2021-08-14 20:46 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +policy_list = security_instance.list_network_security_policy(setDefault)
Fixed

2021-08-14 20:47 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +                    print(rule)
Fixed

2021-08-14 21:26 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +                # Iterate over the "from" ip addresses of each rule
Fixed

2021-08-14 22:01 UTC, vihaanko commented on pyclient/apps/find_rule.py
> +    print("No policies include your ip address.")
Fixed, a IP address can now be taken as an input.

2021-08-17 00:31 UTC, jainvipin approved these changes
LGTM

2021-08-17 00:31 UTC, merged