find tech support data for PSM and DSC nodes corresponding to user specified workloads
pensando/psm-tools pull request #52
Opened 2021-08-05 19:14 UTC by dmachineni

2021-08-06 08:33 UTC, jainvipin requested changes
@dmachineni - thanks for the PR! please address some of the comments here and resubmit the PR.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +        print (arg_file)
remove debug prints, ore put them under --debug flag

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +        tenant = "default"
why is tenant variable declared for three lines of code; defined tenant up at the top that can take this as an arg  if needed. and override that from the input paremeter.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +        namespace = "techsupport"
namespace can be passed as is, not important to save it from a variable i.e. use directly the constant value, not assign to a variable then use it in the assignment.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +        saveBinary(download_path, response.data)
@RishabhPatil - can this routine return an error? if yes, then pls handle the error returned from this function.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +parser.add_argument("-t", "--tenant", dest =  "tenant", default="default", metavar = '', required = False, help = 'tenant name, if not specified: default')
we can add one more arg to avoid posting the techsupport request; this could avoid user from posting a new request  if the request already exists. e.g. if the request is not completed then user might want to avoid doing another post

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +#adds PSM names to node_names set
it would be good to trigger psm nodes techsupport collection using a flag, the default can be true, but user can choose if he or she doesn't want it.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +monitoring_instance.add_tech_support_request(body)
do you want to check the return code of this function? if it errors out you want to exit here.
Also post this command only if user doesn't want you to skip posting tech-support request.

2021-08-06 08:33 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +node_names = list(node_names)
error out if this list is empty here...
esp if you give user an option to avoid psm nodes to be collecting the techsupport data for, this can be empty if no DSC matches the specified workload(s)

2021-08-06 15:00 UTC, RishabhPatil commented on pyclient/apps/find_workload_tech_support.py
> +        saveBinary(download_path, response.data)
I think there are potential permission errors, I'll handle that in the util function and also I'm adding the missing error, when objstore saves an empty file instead of raising an exception.

2021-08-06 20:34 UTC, RishabhPatil requested changes

2021-08-06 20:50 UTC, jainvipin commented on pyclient/apps/find_workload_tech_support.py
> +if (args.collectPSMNodes == "True"):
may be change to `if args.collectPSMNodes:`

2021-08-07 00:30 UTC, RishabhPatil approved these changes
LGTM!

2021-08-07 00:30 UTC, jainvipin approved these changes
LGTM!

2021-08-07 00:30 UTC, merged