issue #19: Find fwlogs given workload names
pensando/psm-tools pull request #53
Opened 2021-08-06 00:14 UTC by lindalwang

2021-08-06 18:20 UTC, jainvipin requested changes
@lindalwang - thanks for the PR; few comments...

2021-08-06 18:20 UTC, jainvipin commented on pyclient/apps/fwlogs.py
> +parser.add_argument("--from", dest="source", help="source workload name")
does it make sense to make this to `--source` and `--destination` because the CLI output shows source destination and cli input takes from and to.

2021-08-06 18:20 UTC, jainvipin commented on pyclient/apps/fwlogs.py
> +parser.add_argument("--from", dest="source", help="source workload name")
enhancement: independently it would be good to take IP address in this command as well and if there is an IP specified we use to find the logs based on the IP; this can be done in subsequent PR or later.

2021-08-06 18:20 UTC, jainvipin commented on pyclient/apps/fwlogs.py
> +if args.duration:
it would be good to take out the time parsing as a utility used by many other programs.

2021-08-06 18:20 UTC, jainvipin commented on pyclient/apps/fwlogs.py
> +parser.add_argument("--to", dest="dest", help = "destination workload name" )
the help says `destination workload name` however if I give partial name it matches too. I think it is a good feature to do partial match, but then update the help to say that you can accept part of the name of the workload as well. e.g. 
```
# ./apps/fwlogs.py --to workload-host-2-w      
creation time              source workload      source ip    destination workload    destination ip    protocol    reporter id
-------------------------  -------------------  -----------  ----------------------  ----------------  ----------  --------------
2021-08-05 22:08:29+00:00  workload-host-2-w0   22.1.0.5     workload-host-2-w12     22.1.0.8          TCP         00ae.cd00.1a10
2021-08-05 22:08:08+00:00  workload-host-2-w0   22.1.0.5     workload-host-2-w12     22.1.0.8          TCP         00ae.cd00.1a10
2021-08-05 22:07:34+00:00  workload-host-2-w12  22.1.0.8     workload-host-2-w0      22.1.0.5          ICMP        00ae.cd00.1a10
2021-08-05 22:07:22+00:00  workload-host-2-w12  22.1.0.8     workload-host-2-w0      22.1.0.5          ICMP        00ae.cd00.1a10
```

2021-08-06 18:20 UTC, jainvipin commented on pyclient/apps/fwlogs.py
> +workloads = workload_list['items']
this way of accessing it as dictionary is very unreadable and also error prone. can you simplify the entire code to something like this, which I tried and it seems to work ok. @RishabhPatil - any comments?
```
workloads = workload_list.items

if args.source:
    source_workload = args.source
    for workload in workloads:
        if source_workload in workload.meta.name:
            for address in workload.spec.interfaces[0].ip_addresses:
```

2021-08-06 19:47 UTC, RishabhPatil requested changes

2021-08-06 19:55 UTC, lindalwang commented on pyclient/apps/fwlogs.py
> +parser.add_argument("--to", dest="dest", help = "destination workload name" )
Ok I changed the help

2021-08-06 19:55 UTC, lindalwang commented on pyclient/apps/fwlogs.py
> +parser.add_argument("--from", dest="source", help="source workload name")
Yes, I think that makes sense. I did from and to because it was in the example. I'll change the options now.

2021-08-06 20:21 UTC, RishabhPatil requested changes
I think adding 'source-name' and 'dest-name' to logs can be more efficient. If you create a hashmap of ip-addresses to workloads, for each log check if the ip-address is in the hashmap or not and add the names accordingly.

You would only have to loop over workloads and logs once each.

2021-08-06 20:21 UTC, RishabhPatil commented on pyclient/apps/fwlogs.py
> +fw_list = api_instance.get_get_logs1()
Instead of fetching all the logs you can use the `post_get_logs` which allows you to narrow down your search.
Also the fwlog query has a max limit of logs it can return per query (its 8192 afaik), all the more reason to filter logs

2021-08-06 20:21 UTC, RishabhPatil commented on pyclient/apps/fwlogs.py
> +                for address in workload['spec']['interfaces'][0]['ip_addresses']:
instead of looping over all the addresses you can do
```
workload_addresses = workload.spec.interfaces[0].ip_addresses
for log in items:
    if log.source_ip in workload_addresses:
        //append to new_list

2021-08-06 21:12 UTC, lindalwang commented on pyclient/apps/fwlogs.py
> +                for address in workload['spec']['interfaces'][0]['ip_addresses']:
thanks that's a lot simpler

2021-08-07 06:21 UTC, jainvipin commented
LGTM!

2021-08-07 06:22 UTC, jainvipin approved these changes

2021-08-07 06:22 UTC, merged