Issue #14
pensando/psm-tools pull request #57
Opened 2021-08-11 17:03 UTC by kiwb

2021-08-11 23:55 UTC, jainvipin requested changes
@kiwb - some comments; I am also failing here when I try to run the app
``` python3 ./apps/identify_dsc.py 
Traceback (most recent call last):
  File "./apps/identify_dsc.py", line 6, in <module>
    from utils.workload_utils import getDscFromWorkload 
ModuleNotFoundError: No module named 'utils.workload_utils'```

2021-08-11 23:55 UTC, jainvipin commented on pyclient/apps/identify_dsc.py
> +import os
pls put #!/usr/bin/python3 at the top of hte file and make this script an execute permissions.
Can you also include a comment about what this utility does? may be in a help string.

2021-08-11 23:55 UTC, jainvipin commented on pyclient/apps/identify_dsc.py
> +    else:
can we display help in this case? using argsparse would be better here. Pls see other programs that use the same.

2021-08-11 23:55 UTC, jainvipin commented on pyclient/apps/identify_dsc.py
> +    print("List of DSC's that meet query:")
minor: this comment is not useful, you can remove it.

2021-08-14 01:06 UTC, RishabhPatil approved these changes
LGTM!

2021-08-14 01:07 UTC, jainvipin approved these changes
LGTM

2021-08-14 01:07 UTC, merged