Go Gen
pensando/psm-tools pull request #78
Opened 2021-10-16 02:41 UTC by RishabhPatil

* Use `make gen go ent` to generate go client files
* Moved generation, preprocessing and postprocessing scripts to `client/scripts/` directory
* Separate folders for python and golang
* Added `cluster_ping.go` example under `go/examples/`

2021-10-19 04:21 UTC, jainvipin requested changes
@RishabhPatil  - thanks for the PR; let's do an offline review to address some base comments and any restructuring that we may need as a result.

2021-10-19 04:21 UTC, jainvipin commented on pyclient/apps/go/cluster_ping.go
> +	"github.com/pensando/psm-go/psm_ent"
is psm-go a top level repo in pensando org? And is it expected to only have generated code? If unsure, for now can you point it to `psm-tools/psmclient/go/psm_ent` in this PR while we discuss the generated code like we did for pypi?

2021-10-19 04:21 UTC, jainvipin commented on pyclient/apps/go/cluster_ping.go
> +	ctx := context.Background()
do w need to cancel this context with defer?

2021-10-19 04:21 UTC, jainvipin commented on pyclient/apps/go/cluster_ping.go
> +		node_health := conditions[0].Type
can you assume condition [0] will always be status? This code needs a bit of work to loop through all conditions and look for the relevant ones maybe?

2021-10-19 04:21 UTC, jainvipin commented on pyclient/apps/go/go.mod
> +module examples
pyclient having `go` and `go.mod` seems a bit strange... can we organize the structure a bit better?
are these packages needed only for the apps? and nothing for the code generation?

2021-10-19 04:21 UTC, jainvipin commented on pyclient/apps/utils/helper.py
> +            raise e
this change seem unrelated to the go generation? can we take it out and keep in a different PR, if needed?

2021-10-20 00:39 UTC, jsilberm commented
pyclient/gogen_ent.sh, pyclient/gogenconfig_ent.json :  Don't these should be included, since they're generated files

2021-11-12 18:35 UTC, jainvipin approved these changes
LGTM

2021-11-12 18:36 UTC, merged